prune_ratios:
  blocks.0.0.conv_dw.weight: 0.0
  blocks.0.0.conv_pw.weight: 0.0
  blocks.0.0.se.conv_expand.weight: 0.0
  blocks.0.0.se.conv_reduce.weight: 0.0
  blocks.1.0.conv_dw.weight: 0.0
  blocks.1.0.conv_pw.weight: 0.0
  blocks.1.0.conv_pwl.weight: 0.0
  blocks.1.0.se.conv_expand.weight: 0.0
  blocks.1.0.se.conv_reduce.weight: 0.0
  blocks.1.1.conv_dw.weight: 0.0
  blocks.1.1.conv_pw.weight: 0.0
  blocks.1.1.conv_pwl.weight: 0.0
  blocks.1.1.se.conv_expand.weight: 0.0
  blocks.1.1.se.conv_reduce.weight: 0.0
  blocks.2.0.conv_dw.weight: 0.0
  blocks.2.0.conv_pw.weight: 0.0
  blocks.2.0.conv_pwl.weight: 0.0
  blocks.2.0.se.conv_expand.weight: 0.0
  blocks.2.0.se.conv_reduce.weight: 0.0
  blocks.2.1.conv_dw.weight: 0.0
  blocks.2.1.conv_pw.weight: 0.0
  blocks.2.1.conv_pwl.weight: 0.0
  blocks.2.1.se.conv_expand.weight: 0.0
  blocks.2.1.se.conv_reduce.weight: 0.0
  blocks.3.0.conv_dw.weight: 0.0
  blocks.3.0.conv_pw.weight: 0.0
  blocks.3.0.conv_pwl.weight: 0.36170370370370375
  blocks.3.0.se.conv_expand.weight: 0.0
  blocks.3.0.se.conv_reduce.weight: 0.0
  blocks.3.1.conv_dw.weight: 0.0
  blocks.3.1.conv_pw.weight: 0.4429774557165861
  blocks.3.1.conv_pwl.weight: 0.4429774557165861
  blocks.3.1.se.conv_expand.weight: 0.0
  blocks.3.1.se.conv_reduce.weight: 0.0
  blocks.3.2.conv_dw.weight: 0.0
  blocks.3.2.conv_pw.weight: 0.4429774557165861
  blocks.3.2.conv_pwl.weight: 0.4429774557165861
  blocks.3.2.se.conv_expand.weight: 0.0
  blocks.3.2.se.conv_reduce.weight: 0.0
  blocks.4.0.conv_dw.weight: 0.0
  blocks.4.0.conv_pw.weight: 0.4429774557165861
  blocks.4.0.conv_pwl.weight: 0.579472049689441
  blocks.4.0.se.conv_expand.weight: 0.0
  blocks.4.0.se.conv_reduce.weight: 0.0
  blocks.4.1.conv_dw.weight: 0.0
  blocks.4.1.conv_pw.weight: 0.6025313023760228
  blocks.4.1.conv_pwl.weight: 0.6025313023760228
  blocks.4.1.se.conv_expand.weight: 0.0
  blocks.4.1.se.conv_reduce.weight: 0.0
  blocks.4.2.conv_dw.weight: 0.0
  blocks.4.2.conv_pw.weight: 0.6025313023760228
  blocks.4.2.conv_pwl.weight: 0.6025313023760228
  blocks.4.2.se.conv_expand.weight: 0.0
  blocks.4.2.se.conv_reduce.weight: 0.0
  blocks.5.0.conv_dw.weight: 0.0
  blocks.5.0.conv_pw.weight: 0.6025313023760228
  blocks.5.0.conv_pwl.weight: 0.744544609309102
  blocks.5.0.se.conv_expand.weight: 0.0
  blocks.5.0.se.conv_reduce.weight: 0.0
  blocks.5.1.conv_dw.weight: 0.0
  blocks.5.1.conv_pw.weight: 0.7683890789944534
  blocks.5.1.conv_pwl.weight: 0.7683890789944534
  blocks.5.1.se.conv_expand.weight: 0.17267064770084095
  blocks.5.1.se.conv_reduce.weight: 0.17267064770084095
  blocks.5.2.conv_dw.weight: 0.0
  blocks.5.2.conv_pw.weight: 0.7683890789944534
  blocks.5.2.conv_pwl.weight: 0.7683890789944534
  blocks.5.2.se.conv_expand.weight: 0.17267064770084095
  blocks.5.2.se.conv_reduce.weight: 0.17267064770084095
  blocks.5.3.conv_dw.weight: 0.0
  blocks.5.3.conv_pw.weight: 0.7683890789944534
  blocks.5.3.conv_pwl.weight: 0.7683890789944534
  blocks.5.3.se.conv_expand.weight: 0.17267064770084095
  blocks.5.3.se.conv_reduce.weight: 0.17267064770084095
  blocks.6.0.conv_dw.weight: 0.0
  blocks.6.0.conv_pw.weight: 0.7683890789944534
  blocks.6.0.conv_pwl.weight: 0.847818203166935
  blocks.6.0.se.conv_expand.weight: 0.17267064770084095
  blocks.6.0.se.conv_reduce.weight: 0.17267064770084095
  conv_head.weight: 0.8511426630434783
